/**
 * CLI script: npm run export:pdf -- --run-id <uuid> --output <path>
 *
 * Generates a simple HTML summary (open in browser and print to PDF).
 * For true PDF generation, integrate puppeteer in production.
 */
import { Pool } from 'pg';
import fs from 'fs';

const pool = new Pool({
  connectionString: process.env.POSTGRES_URL || 'postgresql://farmintel:farmintel@localhost:5432/farmintel',
});

async function main() {
  const args = process.argv.slice(2);
  const runIdIdx = args.indexOf('--run-id');
  const outputIdx = args.indexOf('--output');

  if (runIdIdx === -1) {
    console.error('Usage: npm run export:pdf -- --run-id <uuid> [--output <path>]');
    process.exit(1);
  }

  const runId = args[runIdIdx + 1];
  const outputPath = outputIdx !== -1 ? args[outputIdx + 1] : `summary-${runId.slice(0, 8)}.html`;

  const client = await pool.connect();
  try {
    const runResult = await client.query(
      `SELECT r.*, c.name as campaign_name, c.county, c.state, c.goal_type
       FROM runs r JOIN campaigns c ON c.id = r.campaign_id
       WHERE r.id = $1`,
      [runId]
    );
    const run = runResult.rows[0];
    if (!run) {
      console.error('Run not found');
      process.exit(1);
    }

    const zonesResult = await client.query(
      'SELECT * FROM zones WHERE run_id = $1 ORDER BY score_total DESC LIMIT 20',
      [runId]
    );

    const rows = zonesResult.rows.map((z: any, i: number) => {
      const comp = typeof z.score_components === 'string' ? JSON.parse(z.score_components) : z.score_components;
      return `<tr>
        <td>${i + 1}</td>
        <td>${z.zone_name || z.zone_id}</td>
        <td><strong>${z.score_total.toFixed(1)}</strong></td>
        <td>${z.parcel_count}</td>
        <td>${comp?.reason || '-'}</td>
      </tr>`;
    });

    const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>FarmIntel Summary</title>
<style>
  body{font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:20px}
  h1{color:#054b85;font-size:20px}
  table{width:100%;border-collapse:collapse;font-size:12px}
  th{background:#f1f5f9;text-align:left;padding:6px;border-bottom:2px solid #e2e8f0}
  td{padding:6px;border-bottom:1px solid #e2e8f0}
</style></head><body>
<h1>${run.campaign_name} — Zone Summary</h1>
<p>${run.county || ''} ${run.state || ''} — ${run.goal_type} prospecting — ${new Date().toLocaleDateString()}</p>
<table><thead><tr><th>#</th><th>Zone</th><th>Score</th><th>Parcels</th><th>Reason</th></tr></thead>
<tbody>${rows.join('')}</tbody></table>
<p style="color:#999;font-size:11px;margin-top:20px">Generated by FarmIntel — TD Realty Ohio</p>
</body></html>`;

    fs.writeFileSync(outputPath, html);
    console.log(`Exported summary to ${outputPath} (open in browser and print to PDF)`);
  } finally {
    client.release();
    await pool.end();
  }
}

main();
