import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { query, queryOne } from '@/lib/db';

export async function GET(
  req: NextRequest,
  { params }: { params: { runId: string } }
) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const url = new URL(req.url);
  const zoneFilter = url.searchParams.get('zone');

  // Get run and campaign info
  const run = await queryOne(
    `SELECT r.*, c.name as campaign_name, c.county, c.state, c.goal_type
     FROM runs r JOIN campaigns c ON c.id = r.campaign_id
     WHERE r.id = $1`,
    [params.runId]
  );
  if (!run) {
    return NextResponse.json({ error: 'Run not found' }, { status: 404 });
  }

  let zones;
  if (zoneFilter) {
    zones = await query(
      'SELECT * FROM zones WHERE run_id = $1 AND (zone_id = $2 OR id::text = $2) ORDER BY score_total DESC',
      [params.runId, zoneFilter]
    );
  } else {
    zones = await query(
      'SELECT * FROM zones WHERE run_id = $1 ORDER BY score_total DESC LIMIT 20',
      [params.runId]
    );
  }

  // Build HTML-based PDF using a simple approach
  const html = buildPDFHTML(run, zones);

  // Return as HTML that can be printed to PDF
  // For true server-side PDF, integrate puppeteer or pdfkit in production
  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html',
      'Content-Disposition': `inline; filename="farmintel-summary-${params.runId.slice(0, 8)}.html"`,
    },
  });
}

function buildPDFHTML(run: any, zones: any[]): string {
  const zoneRows = zones.map((z, i) => {
    const components = typeof z.score_components === 'string'
      ? JSON.parse(z.score_components)
      : z.score_components;
    return `
      <tr>
        <td>${i + 1}</td>
        <td>${z.zone_name || z.zone_id}</td>
        <td><strong>${z.score_total.toFixed(1)}</strong></td>
        <td>${z.parcel_count}</td>
        <td>${z.transfer_count_10y}</td>
        <td style="font-size:11px">${components?.reason || '-'}</td>
        <td>${getRecommendedCadence(z.score_total)}</td>
      </tr>`;
  });

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>FarmIntel Zone Summary</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; color: #1a1a1a; }
    h1 { font-size: 22px; color: #054b85; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 14px; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { background: #f1f5f9; text-align: left; padding: 8px; border-bottom: 2px solid #e2e8f0; }
    td { padding: 8px; border-bottom: 1px solid #e2e8f0; }
    tr:hover { background: #f8fafc; }
    .metrics { display: flex; gap: 20px; margin-bottom: 20px; }
    .metric { background: #f1f5f9; padding: 12px 16px; border-radius: 8px; }
    .metric .value { font-size: 20px; font-weight: bold; color: #054b85; }
    .metric .label { font-size: 11px; color: #666; }
    .footer { margin-top: 30px; font-size: 11px; color: #999; border-top: 1px solid #e2e8f0; padding-top: 10px; }
    @media print { body { padding: 0; } }
  </style>
</head>
<body>
  <h1>FarmIntel Zone Summary</h1>
  <p class="subtitle">
    ${run.campaign_name} &mdash; ${run.county ? `${run.county}, ${run.state}` : ''} &mdash; ${run.goal_type} prospecting
  </p>

  <div class="metrics">
    <div class="metric">
      <div class="value">${zones.length}</div>
      <div class="label">Zones Scored</div>
    </div>
    <div class="metric">
      <div class="value">${zones.reduce((s: number, z: any) => s + z.parcel_count, 0).toLocaleString()}</div>
      <div class="label">Total Parcels</div>
    </div>
    <div class="metric">
      <div class="value">${zones.length > 0 ? zones[0].score_total.toFixed(1) : '-'}</div>
      <div class="label">Top Zone Score</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Zone</th>
        <th>Score</th>
        <th>Parcels</th>
        <th>Transfers (10y)</th>
        <th>Key Reason</th>
        <th>Recommended Cadence</th>
      </tr>
    </thead>
    <tbody>
      ${zoneRows.join('')}
    </tbody>
  </table>

  <div class="footer">
    Generated by FarmIntel &mdash; TD Realty Ohio &mdash; ${new Date().toLocaleDateString()}<br>
    Print this page or use browser "Save as PDF" for a PDF copy.
  </div>
</body>
</html>`;
}

function getRecommendedCadence(score: number): string {
  if (score >= 60) return 'Monthly (door + mail)';
  if (score >= 40) return 'Quarterly (mail)';
  return 'Semi-annual (mail)';
}
